services:
  redis:
    container_name: foundrycache
    image: redis
    volumes:
      - redis:/data
    restart: always
    networks:
      - foundry

  foundryapi:
    container_name: foundryapi
    build:
      context: .
      dockerfile: Dockerfile.api.production
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      UPLOADS_DIR: /app/uploads
    env_file:
      - ./.env
    ports:
      - 3007:3000
    volumes:
      - uploads:/app/uploads
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - foundry

  foundryclient:
    container_name: foundryclient
    build:
      context: .
      dockerfile: Dockerfile.client.production
    ports:
      - 8083:80
    depends_on:
      foundryapi:
        condition: service_started
    restart: always
    networks:
      - foundry

volumes:
  postgres_data:
  redis:
  uploads:

networks:
  foundry:
    name: foundry
